# Docker Compose 本地开发配置文件
# 用于本地开发环境下定义和运行容器化应用
#
# 常用命令:
# 启动开发环境:    docker compose -f docker-compose-local.yml up -d
# 停止开发环境:    docker compose -f docker-compose-local.yml down
# 查看开发日志:    docker compose -f docker-compose-local.yml logs -f
# 重新构建开发环境: docker compose -f docker-compose-local.yml build
# 重启开发服务:    docker compose -f docker-compose-local.yml restart
#
# 完全重建开发环境:
# docker compose -f docker-compose-local.yml down
# docker compose -f docker-compose-local.yml build --no-cache
#
# 版本说明:
# version '3.8' 支持 Docker 19.03.0+ 版本

version: '3.8'

services:
  # FastAPI 开发服务
  app:
    image: fastapi-dev:latest
    # 设置开发容器名称
    container_name: fastapi-dev   # 开发环境容器名称
    # 使用当前目录的 Dockerfile 构建开发容器
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always  # 开发容器崩溃时自动重启
    
    # 端口映射配置
    # 将开发容器的 8000 端口映射到主机的 8000 端口
    ports:
      - "8000:8000"
    volumes:
      - ./app:/WORKDIR/app
    # 加载本地开发环境变量
    env_file:
      - .env

    # 启动开发服务
    command: /WORKDIR/start.sh
