"""增加未完成todo查询

Revision ID: 3458efff10ba
Revises: fd01d531c6c5
Create Date: 2025-03-14 09:19:24.747086

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3458efff10ba'
down_revision = 'fd01d531c6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
