"""user_todo_relation_upgrade_again

Revision ID: 6f299294d684
Revises: e83fc7777bd5
Create Date: 2025-03-14 12:40:50.221721

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6f299294d684'
down_revision = 'e83fc7777bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
