"""test迁移

Revision ID: fd01d531c6c5
Revises: 943b2efc1fc5
Create Date: 2025-03-14 09:12:21.008674

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fd01d531c6c5'
down_revision = '943b2efc1fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
